[project]
name = "unified-experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Noah Jutz", email = "git@noahjutz.anonaddy.com" }
]
requires-python = ">=3.10.1, <=3.10.12"
dependencies = [
    "gymnasium>=1.2.2",
    "mlagents>=1.1.0",
    "mlagents-envs>=1.1.0",
    "onnxruntime>=1.23.2",
    "ray[rllib]>=2.59.0",
    "shimmy>=2.0.1",
    "torch>=2.14.1",
]

[project.scripts]
unified-experiments = "unified_experiments.main:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
