[project]
name = "hfrl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Noah Jutz", email = "git@noahjutz.anonaddy.com" }
]
requires-python = ">=3.13,<3.14"
dependencies = [
    "gymnasium[box2d]>=1.3.0",
    "huggingface-sb3>=3.0",
    "shimmy>=2.0.1",
    "stable-baselines3[extra]>=2.9.0",
    "swig>=4,<4.5",
]

[tool.basedpyright]
typeCheckingMode = "off"

[project.scripts]
hfrl = "hfrl.main:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
