[project]
name = "hfrl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Noah Jutz", email = "git@noahjutz.anonaddy.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
hfrl = "hfrl.main:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
