[project]
name = "weekly-schedule-yml"
version = "0.1.0"
description = "Convert YAML to iCal"
readme = "README.md"
authors = [
    { name = "Noah Jutz", email = "git@noahjutz.anonaddy.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
yml2ical = "weekly_schedule_yml.main:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
