[project]
name = "jax_hello"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Noah Jutz", email = "noah@noahjutz.com" }
]
requires-python = ">=3.14"
dependencies = [
    "jax>=0.11.1",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
]

[project.scripts]
jax_hello = "jax_hello.main:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
