[project]
name = "gym_app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Noah Jutz", email = "git@noahjutz.anonaddy.com" }
]
requires-python = ">=3.14"
dependencies = [
    "gymnasium[classic-control]>=1.3.0",
    "matplotlib>=3.11.1",
    "pyinstrument>=5.1.3",
]

[project.scripts]
gym = "gym_app.main:main"

[tool.basedpyright]
typeCheckingMode = "off"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
