services:
  ray-head:
    image: docker.io/rayproject/ray:2.58.0-py313-gpu
    command: ray start --head --block --dashboard-host 0.0.0.0 --temp-dir ${RAY_TEMP_DIR}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    env_file: .env
    environment:
      RAY_PROMETHEUS_HOST: http://prometheus:9090
      RAY_GRAFANA_HOST: http://grafana:3000
      RAY_GRAFANA_IFRAME_HOST: http://127.0.0.1:3000
      RAY_TEMP_DIR: ${RAY_TEMP_DIR}
      UV_LINK_MODE: copy
      UV_CACHE_DIR: /home/ray/.cache/uv
    healthcheck:
      test: python -c 'import urllib.request; urllib.request.urlopen("http://127.0.0.1:8265/api/version")'
    shm_size: 4.64gb
    ports:
      - 8265:8265
      - 6379:6379
    networks:
      - raynet
    volumes:
      - ray-tmp:${RAY_TEMP_DIR}
      - ~/.cache/uv:/home/ray/.cache/uv:z
  prometheus:
    image: docker.io/prom/prometheus:v3.14.0-distroless
    depends_on:
      ray-head:
        condition: service_healthy
    command:
      - "--config.file=${RAY_TEMP_DIR}/session_latest/metrics/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    networks:
      - raynet
    volumes:
      - ray-tmp:${RAY_TEMP_DIR}
  grafana:
    image: docker.io/grafana/grafana:13.0.8
    depends_on:
      ray-head:
        condition: service_healthy
    command:
      - "--config=${RAY_TEMP_DIR}/session_latest/metrics/grafana/grafana.ini"
      - "web"
    environment:
      - GF_PATHS_PROVISIONING=${RAY_TEMP_DIR}/session_latest/metrics/grafana/provisioning
    ports:
      - 3000:3000
    networks:
      - raynet
    volumes:
      - ray-tmp:${RAY_TEMP_DIR}

volumes:
  ray-tmp:

networks:
  raynet:
