services:
  prom:
    image: docker.io/prom/prometheus:v3.14.0-distroless
    depends_on:
      dreamer:
        condition: service_healthy
    command:
      - "--config.file=${RAY_TEMP_DIR}/session_latest/metrics/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    networks:
      - raynet
    volumes:
      - ray-tmp:${RAY_TEMP_DIR}
  grafana:
    image: docker.io/grafana/grafana:13.0.8
    depends_on:
      dreamer:
        condition: service_healthy
    command:
      - "--config=${RAY_TEMP_DIR}/session_latest/metrics/grafana/grafana.ini"
      - "web"
    environment:
      - GF_PATHS_PROVISIONING=${RAY_TEMP_DIR}/session_latest/metrics/grafana/provisioning
    ports:
      - 3000:3000
    networks:
      - raynet
    volumes:
      - ray-tmp:${RAY_TEMP_DIR}
  dreamer:
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      RAY_PROMETHEUS_HOST: http://prom:9090
      RAY_GRAFANA_HOST: http://grafana:3000
      RAY_GRAFANA_IFRAME_HOST: http://127.0.0.1:3000
      RAY_TEMP_DIR: ${RAY_TEMP_DIR}
    env_file:
      .env
    healthcheck:
      test: uv run python -c 'import urllib.request; urllib.request.urlopen("http://127.0.0.1:8265/api/version")'
    shm_size: 4.64gb
    ports:
      - 8265:8265
    networks:
      - raynet
    volumes:
      - ray-tmp:${RAY_TEMP_DIR}


volumes:
  ray-tmp:

networks:
  raynet:
