[project]
name = "hello_torchrl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Noah Jutz", email = "git@noahjutz.anonaddy.com" }
]
requires-python = ">=3.12,<3.14"
dependencies = [
    "flappy-bird-gymnasium>=0.4.0",
    "gymnasium>=1.2.2",
    "ray[rllib]>=2.58.0",
    "tensordict>=0.13.0",
    "torchrl>=0.13.3",
]

[tool.basedpyright]
typeCheckingMode = "off"

[project.scripts]
trl = "hello_torchrl.main:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
