FROM docker.io/alpine/git:latest AS fetch

ARG DREAMER_COMMIT_SHA=e3f02248693a79dc8b0ebd62c93683888ddaccfe

WORKDIR /app

RUN git clone --depth 1 https://github.com/danijar/dreamerv3.git && \
    cd dreamerv3 && \
    git fetch --depth 1 origin ${DREAMER_COMMIT_SHA} && \
    git checkout ${DREAMER_COMMIT_SHA} && \
    rm -rf .git

FROM ghcr.io/astral-sh/uv:python3.11-alpine AS build

WORKDIR /app

COPY requirements.txt .

RUN uv init && \
    uv add -r requirements.txt
