[workspace]
authors = ["Noah Jutz <git@noahjutz.anonaddy.com>"]
channels = ["conda-forge"]
name = "hello_dreamerv3"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
dreamer = "pixi run python -m dreamerv3.main"
wrapper = "PYTHONPATH=src pixi run python -m hello_dreamerv3.main"

[dependencies]
python = "3.11.*"
gymnasium = ">=1.3.0,<2"

[pypi-dependencies]
dreamer = { git = "https://github.com/noahjutz/dreamerv3.git", rev = "9ad0d98934a19f0b7ff7b2c622598285895d6534" }
