[project]
name = "hello_pytorch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Noah Jutz", email = "git@noahjutz.anonaddy.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.2",
    "requests>=2.34.2",
    "scikit-learn>=1.9.1",
    "tensordict>=0.14.0",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
]

[project.scripts]
linear = "hello_pytorch.linear_regression.train:main"
linear_eval = "hello_pytorch.linear_regression.eval:main"
class_binary = "hello_pytorch.classification.binary:main"
class_multi = "hello_pytorch.classification.multiclass:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
