from collections.abc import Callable

import numpy as np
from numpy.typing import NDArray


def p_pi(a: int, s: tuple[int, int, int, int], Q: NDArray, epsilon: float = 0) -> float:
    """
    Args:
        a: Action (0 or 1)
        s: State
        Q: state-action values
        epsilon: Exploration rate
    Returns:
        probability of choosing a in s in [0, 1]
    Probability Pr(a | s) for an epsilon-greedy policy w.r.t action-values Q
    """
    p_e = epsilon / 2  # explore
    p_g = 1 - epsilon  # exploit
    is_greedy_a = a == np.argmax(Q[s], axis=-1)
    if is_greedy_a:
        return p_g + p_e
    else:
        return p_e


def isr(epsilon: float, Q: NDArray, action: int, state: NDArray) -> float:
    """
    One factor of the Incremental Importance-Sampling Ratio for
    - an epsilon-greedy behavior policy b
    - a greedy target policy pi
    with the same state-action values Q.
    """

    A = 2  # amount of actions A(s)

    def ratio():
        a = action
        s = tuple(state)
        if p_pi(a, s, epsilon=epsilon) == 0:
            return 0
        return p_pi(a, s) / p_pi(a, s, epsilon=epsilon)

    return ratio()


def monte_carlo(
    rewards: NDArray[np.float64],
    states: NDArray[np.uint32],
    actions: NDArray[np.uint32],
    gamma: float,
    epsilon: float,
    C: NDArray,
    Q: NDArray,
) -> tuple[NDArray, NDArray]:
    """
    First-Visit MC prediction for pi, given one T-step episode generated by b, using weighted importance sampling
    Args:
        rewards: (T,)
        states: (T, 4)
        actions: (T,)
        gamma: Discount factor
        epsilon: Exploring Rate
        C: (*n_bins, 2) Cumulative weight for each state
        Q: (*n_bins, 2) state-action value
    Returns:
        C, Q
    """
    T = len(rewards)
    # Build set of first-visit timesteps: for each (state, action) pair,
    # only the earliest timestep counts.
    first_visit: dict[tuple, int] = {}
    for t in range(T):
        key = (*states[t], actions[t])
        if key not in first_visit:
            first_visit[key] = t

    # Backward pass to compute returns
    G = 0.0
    W = 1
    for t in range(T - 1, -1, -1):
        G = gamma * G + rewards[t]

        key = (*states[t], actions[t])
        if first_visit[key] == t:
            idx = tuple(key)
            C[idx] += W
            Q[idx] += (W / C[idx]) * (G - Q[idx])

        W *= isr(epsilon, Q, actions[t], states[t])
        if W == 0:
            break
    return C, Q


def sarsa(
    Q: NDArray[np.float64],
    alpha: float,
    gamma: float,
    old_sa: tuple[int, int, int, int, int],
    sa: tuple[int, int, int, int, int],
    r: float,
    is_T: bool,
) -> NDArray:
    """
    Sarsa (tabular, one-step TD, on-policy).

    Args:
        Q: (*n_bins, 2) state-action value estimate
        alpha: Step size
        gamma: Discount factor
        old_sa: state-action pair at step t
        sa: state-action pair at step (t+1)
        r: reward at step (t+1)
    Returns:
        Q: (*n_bins, 2) next state_action value estimate
    """

    error = r + gamma * Q[sa] * (1 - is_T) - Q[old_sa]
    Q[old_sa] = Q[old_sa] + alpha * error
    return Q


def q_learning(
    Q: NDArray[np.float64],
    alpha: float,
    gamma: float,
    old_sa: tuple[int, int, int, int, int],
    sa: tuple[int, int, int, int, int],
    r: float,
    is_T: bool,
) -> NDArray:
    """
    Q-learning (tabular, one-step TD, off-policy)

    Args:
        Q: (*n_bins, 2) state-action value estimate
        alpha: Step size
        gamma: Discount factor
        old_sa: state-action pair at step t
        sa: state-action pair at step (t+1)
        r: reward at step (t+1)
    Returns:
        Q: (*n_bins, 2) next state_action value estimate
    """
    s = sa[:-1]
    q_greedy = np.max(Q[s])
    error = r + gamma * q_greedy * (1 - is_T) - Q[old_sa]
    Q[old_sa] = Q[old_sa] + alpha * error
    return Q


def expedced_sarsa(
    Q: NDArray[np.float64],
    alpha: float,
    gamma: float,
    old_sa: tuple[int, int, int, int, int],
    sa: tuple[int, int, int, int, int],
    r: float,
    is_T: bool,
    policy: Callable[[int, int], float],
) -> NDArray:
    """
    Move towards expectation

    Args:
        Q: (*n_bins, 2) state-action value estimate
        alpha: Step size
        gamma: Discount factor
        old_sa: state-action pair at step t
        sa: state-action pair at step (t+1)
        r: reward at step (t+1)
        policy: probability pi(a | s) -> [0, 1]
    Returns:
        Q: (*n_bins, 2) next state_action value estimate
    """

    s = sa[:1]
    expected_q = 0
    for a in range(2):
        p = policy(a, s)
        q = Q[(*s, a)]
        expected_q += p * q

    error = r + gamma * expected_q * (1 - is_T) - Q[sa]
    Q[sa] += alpha * error
    return Q
