import numpy as np
from numpy.typing import NDArray


def isr(epsilon: float, Q: NDArray, action: int, state: NDArray) -> float:
    """
    Incremental Importance-Sampling Ratio (Ordinary Importance Sampling) for
    - an epsilon-greedy behavior policy b
    - a greedy target policy pi
    with the same state-action values Q. Given an episode with actions, states.
    """

    A = 2  # amount of actions A(s)

    # Target Policy (greedy)
    def pi(a: int, s: tuple[int, int, int, int]):
        return a == np.argmax(Q[s], axis=-1)

    # Behavior-policy (epsilon-greedy)
    def b(a: int, s: tuple[int, int, int, int]):
        p_e = epsilon / A  # explore
        p_g = 1 - epsilon  # exploit
        p_pi = pi(a, s)
        if p_pi == 1:  # a=a*
            return p_g + p_e
        elif p_pi == 0:  # a!=a*
            return p_e

    def ratio():
        a = action
        s = tuple(state)
        return pi(a, s) / b(a, s)

    return ratio()


def monte_carlo(
    rewards: NDArray[np.float64],
    states: NDArray[np.uint32],
    actions: NDArray[np.uint32],
    gamma: float,
    epsilon: float,
    C: NDArray,
    Q: NDArray,
) -> tuple[NDArray, NDArray]:
    """
    First-Visit MC prediction for pi, given one T-step episode generated by b, using ordinary importance sampling
    Args:
        rewards: (T,)
        states: (T, 4)
        actions: (T,)
        gamma: Discount factor
        epsilon: Exploring Rate
        C: (n_bins,)*4+(2,); Cumulative weight for each state
        Q: (n_bins,)*4+(2,); state-action value
    Returns:
        C, Q
    """
    T = len(rewards)
    # Build set of first-visit timesteps: for each (state, action) pair,
    # only the earliest timestep counts.
    first_visit: dict[tuple, int] = {}
    for t in range(T):
        key = (*states[t], actions[t])
        if key not in first_visit:
            first_visit[key] = t

    # Backward pass to compute returns
    G = 0.0
    W = 1
    for t in range(T - 1, -1, -1):
        G = gamma * G + rewards[t]

        key = (*states[t], actions[t])
        if first_visit[key] == t:
            idx = tuple(key)
            C[idx] += W
            Q[idx] += (W / C[idx]) * (G - Q[idx])

        W *= isr(epsilon, Q, actions[t], states[t])
        if W == 0:
            break
    return C, Q
